- hosts: all
  become: true
  tasks:
  - name: create docker container
    shell: docker run -d --name ansible_container -p 8090:8080 gurendra/maven-deployment
    shell: docker container update ansible_container CONTAINER gurendra/maven-deployment
